.PHONY: all build clean test test-race run docker docker-up docker-down help server bench-distributed tls-quickstart tls-quickstart-force

BINARY_NAME := kar
BUILD_DIR := bin
GO := go
GOFLAGS := -trimpath
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
BUILD_TIME := $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
LDFLAGS := -s -w -X main.version=$(VERSION) -X main.buildTime=$(BUILD_TIME) -X main.gitCommit=$(GIT_COMMIT)

all: build

## build: Build the kar binary
build:
	@mkdir -p $(BUILD_DIR)
	$(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME) ./cmd/kar98k

## build-all: Build for multiple platforms
build-all:
	@mkdir -p $(BUILD_DIR)
	GOOS=linux GOARCH=amd64 $(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME)-linux-amd64 ./cmd/kar98k
	GOOS=linux GOARCH=arm64 $(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME)-linux-arm64 ./cmd/kar98k
	GOOS=darwin GOARCH=amd64 $(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME)-darwin-amd64 ./cmd/kar98k
	GOOS=darwin GOARCH=arm64 $(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME)-darwin-arm64 ./cmd/kar98k
	GOOS=windows GOARCH=amd64 $(GO) build $(GOFLAGS) -ldflags "$(LDFLAGS)" -o $(BUILD_DIR)/$(BINARY_NAME)-windows-amd64.exe ./cmd/kar98k

## server: Build the sample echo server
server:
	@mkdir -p $(BUILD_DIR)
	$(GO) build $(GOFLAGS) -o $(BUILD_DIR)/echoserver ./examples/echoserver

## clean: Remove build artifacts
clean:
	rm -rf $(BUILD_DIR)
	$(GO) clean

## test: Run tests
test:
	$(GO) test -v ./...

## test-race: Run tests with race detector
test-race:
	$(GO) test -race -v ./...

## test-cover: Run tests with coverage
test-cover:
	$(GO) test -coverprofile=coverage.out ./...
	$(GO) tool cover -html=coverage.out -o coverage.html

## fmt: Format code
fmt:
	$(GO) fmt ./...
	goimports -w .

## run: Run kar (interactive mode)
run: build
	./$(BUILD_DIR)/$(BINARY_NAME) start

## run-server: Run the sample echo server
run-server: server
	./$(BUILD_DIR)/echoserver

## demo: Run full demo (server + kar)
demo: build server
	@echo "Starting echo server in background..."
	@./$(BUILD_DIR)/echoserver &
	@sleep 1
	@echo "Starting kar..."
	./$(BUILD_DIR)/$(BINARY_NAME) run --config examples/demo.yaml --trigger

## docker: Build Docker image
docker:
	docker build -t kar98k:latest .

## docker-up: Start with docker-compose
docker-up:
	docker-compose up -d

## docker-down: Stop docker-compose
docker-down:
	docker-compose down

## proto-deps: Install pinned protoc-gen-go + protoc-gen-go-grpc
proto-deps:
	$(GO) install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
	$(GO) install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

## proto: Regenerate gRPC code from kar.proto (requires protoc binary + plugins from proto-deps)
proto: proto-deps
	protoc --go_out=. --go_opt=paths=source_relative \
	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	       internal/rpc/proto/kar.proto

## deps: Download dependencies
deps:
	$(GO) mod download
	$(GO) mod tidy

## install: Install kar to GOPATH/bin
install: build
	cp $(BUILD_DIR)/$(BINARY_NAME) $(GOPATH)/bin/$(BINARY_NAME)

## bench-distributed: Run hot-add benchmark via docker-compose (manual, supplementary — CI uses TestHotAddRebalance)
bench-distributed:
	./examples/distributed/bench.sh

TLS_LOCAL_DIR := examples/distributed/tls-local
TLS_CERT      := $(TLS_LOCAL_DIR)/insecure.crt
TLS_KEY       := $(TLS_LOCAL_DIR)/insecure.key

## tls-quickstart: Generate a self-signed dev cert pair in examples/distributed/tls-local/ (refuses to overwrite)
tls-quickstart:
	@if [ -f "$(TLS_CERT)" ]; then \
		echo "tls-local/ already populated — refusing to overwrite. Run 'make tls-quickstart-force' to regenerate."; \
		exit 1; \
	fi
	@mkdir -p $(TLS_LOCAL_DIR)
	openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes \
		-keyout $(TLS_KEY) -out $(TLS_CERT) \
		-subj "/CN=kar-dev" \
		-addext "subjectAltName=DNS:localhost,IP:127.0.0.1" && \
		chmod 0600 $(TLS_KEY)
	@printf '# DEV ONLY — DO NOT USE IN PROD\n\nThis directory contains a self-signed certificate pair generated by\n`make tls-quickstart`. These keys are for local development and testing only.\nNever use them in production.\n' > $(TLS_LOCAL_DIR)/README.md
	@echo "Generated TLS cert pair in $(TLS_LOCAL_DIR)/"

## tls-quickstart-force: Regenerate self-signed dev cert pair (overwrites existing)
tls-quickstart-force:
	@rm -f $(TLS_CERT) $(TLS_KEY) $(TLS_LOCAL_DIR)/README.md
	@$(MAKE) tls-quickstart

## help: Show this help
help:
	@echo "Available targets:"
	@sed -n 's/^## //p' $(MAKEFILE_LIST) | column -t -s ':'
