// Code generated by protoc-gen-go. DO NOT EDIT.
// Hand-crafted: protoc not available on this system; see internal/rpc/proto/README.md
// TODO(#52-followup): regenerate via `make proto` once protoc-gen-go@v1.34.x and
// protoc are installed; opaque-state generation in protoc-gen-go >=v1.35 changes
// reflection-path field offsets and may require integration_test.go updates.
// source: kar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_NONE  Command = 0
	Command_START Command = 1
	Command_STOP  Command = 2
	Command_DRAIN Command = 3
)

var (
	Command_name = map[int32]string{
		0: "NONE",
		1: "START",
		2: "STOP",
		3: "DRAIN",
	}
	Command_value = map[string]int32{
		"NONE":  0,
		"START": 1,
		"STOP":  2,
		"DRAIN": 3,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_kar_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_kar_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// HistogramBounds describes the HDR histogram configuration a worker uses.
type HistogramBounds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinValue int64 `protobuf:"varint,1,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue int64 `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	SigFigs  int32 `protobuf:"varint,3,opt,name=sig_figs,json=sigFigs,proto3" json:"sig_figs,omitempty"`
}

func (x *HistogramBounds) Reset() {
	*x = HistogramBounds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *HistogramBounds) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HistogramBounds) ProtoMessage()     {}

func (x *HistogramBounds) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HistogramBounds) GetMinValue() int64 { return x.MinValue }
func (x *HistogramBounds) GetMaxValue() int64 { return x.MaxValue }
func (x *HistogramBounds) GetSigFigs() int32  { return x.SigFigs }

// TargetSpec describes one load target propagated from master to worker.
type TargetSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Protocol  string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method    string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Weight    int32  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	TimeoutMs int64  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *TargetSpec) Reset() {
	*x = TargetSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *TargetSpec) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TargetSpec) ProtoMessage()     {}

func (x *TargetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetSpec) GetName() string      { return x.Name }
func (x *TargetSpec) GetUrl() string       { return x.Url }
func (x *TargetSpec) GetProtocol() string  { return x.Protocol }
func (x *TargetSpec) GetMethod() string    { return x.Method }
func (x *TargetSpec) GetWeight() int32     { return x.Weight }
func (x *TargetSpec) GetTimeoutMs() int64  { return x.TimeoutMs }

// WorkerPoolConfig carries pool sizing from master to worker.
type WorkerPoolConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolSize  int32 `protobuf:"varint,1,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	QueueSize int32 `protobuf:"varint,2,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
}

func (x *WorkerPoolConfig) Reset() {
	*x = WorkerPoolConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *WorkerPoolConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WorkerPoolConfig) ProtoMessage()     {}

func (x *WorkerPoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WorkerPoolConfig) GetPoolSize() int32  { return x.PoolSize }
func (x *WorkerPoolConfig) GetQueueSize() int32 { return x.QueueSize }

// RegisterReq is sent by a worker on startup to join the master.
type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerAddr   string           `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	Version      string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CapacityHint uint64           `protobuf:"varint,3,opt,name=capacity_hint,json=capacityHint,proto3" json:"capacity_hint,omitempty"`
	Bounds       *HistogramBounds `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *RegisterReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterReq) ProtoMessage()     {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterReq) GetWorkerAddr() string        { return x.WorkerAddr }
func (x *RegisterReq) GetVersion() string           { return x.Version }
func (x *RegisterReq) GetCapacityHint() uint64      { return x.CapacityHint }
func (x *RegisterReq) GetBounds() *HistogramBounds  { return x.Bounds }

// RegisterResp is the master's reply to a Register call.
type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId       string           `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Targets        []*TargetSpec    `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Pool           *WorkerPoolConfig `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	StatsIntervalMs uint32          `protobuf:"varint,4,opt,name=stats_interval_ms,json=statsIntervalMs,proto3" json:"stats_interval_ms,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *RegisterResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterResp) ProtoMessage()     {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResp) GetWorkerId() string           { return x.WorkerId }
func (x *RegisterResp) GetTargets() []*TargetSpec     { return x.Targets }
func (x *RegisterResp) GetPool() *WorkerPoolConfig    { return x.Pool }
func (x *RegisterResp) GetStatsIntervalMs() uint32    { return x.StatsIntervalMs }

// RateSubscribeReq opens the server-side rate-update stream.
type RateSubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
}

func (x *RateSubscribeReq) Reset() {
	*x = RateSubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *RateSubscribeReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RateSubscribeReq) ProtoMessage()     {}

func (x *RateSubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RateSubscribeReq) GetWorkerId() string { return x.WorkerId }

// RateUpdate is pushed by the master to each worker at ~10 Hz.
type RateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetTps float64 `protobuf:"fixed64,1,opt,name=target_tps,json=targetTps,proto3" json:"target_tps,omitempty"`
	Command   Command `protobuf:"varint,2,opt,name=command,proto3,enum=kar.rpc.Command" json:"command,omitempty"`
}

func (x *RateUpdate) Reset() {
	*x = RateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *RateUpdate) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RateUpdate) ProtoMessage()     {}

func (x *RateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RateUpdate) GetTargetTps() float64 { return x.TargetTps }
func (x *RateUpdate) GetCommand() Command   { return x.Command }

// StatsPush is sent by a worker every stats_interval_ms.
type StatsPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId     string  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp    uint64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ObservedTps  float64 `protobuf:"fixed64,3,opt,name=observed_tps,json=observedTps,proto3" json:"observed_tps,omitempty"`
	QueueDrops   int64   `protobuf:"varint,4,opt,name=queue_drops,json=queueDrops,proto3" json:"queue_drops,omitempty"`
	HdrRaw       []byte  `protobuf:"bytes,5,opt,name=hdr_raw,json=hdrRaw,proto3" json:"hdr_raw,omitempty"`
	HdrCorrected []byte  `protobuf:"bytes,6,opt,name=hdr_corrected,json=hdrCorrected,proto3" json:"hdr_corrected,omitempty"`
	ErrorRate    float64 `protobuf:"fixed64,7,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
}

func (x *StatsPush) Reset() {
	*x = StatsPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *StatsPush) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StatsPush) ProtoMessage()     {}

func (x *StatsPush) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsPush) GetWorkerId() string     { return x.WorkerId }
func (x *StatsPush) GetTimestamp() uint64    { return x.Timestamp }
func (x *StatsPush) GetObservedTps() float64 { return x.ObservedTps }
func (x *StatsPush) GetQueueDrops() int64    { return x.QueueDrops }
func (x *StatsPush) GetHdrRaw() []byte       { return x.HdrRaw }
func (x *StatsPush) GetHdrCorrected() []byte { return x.HdrCorrected }
func (x *StatsPush) GetErrorRate() float64   { return x.ErrorRate }

// StatsAck is the master's acknowledgment of a Stats stream.
type StatsAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *StatsAck) Reset() {
	*x = StatsAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}
func (x *StatsAck) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StatsAck) ProtoMessage()     {}

func (x *StatsAck) ProtoReflect() protoreflect.Message {
	mi := &file_kar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsAck) GetOk() bool { return x.Ok }

// ---------------------------------------------------------------------------
// File descriptor & init — minimal stubs required by protoimpl reflection.
// These are intentionally simplified; regenerate with protoc for production.
// ---------------------------------------------------------------------------

var file_kar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kar_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kar_proto_rawDescOnce sync.Once
var file_kar_proto_rawDescData []byte

func file_kar_proto_rawDescGZIP() []byte {
	file_kar_proto_rawDescOnce.Do(func() {
		file_kar_proto_rawDescData = []byte{}
	})
	return file_kar_proto_rawDescData
}

var file_kar_proto_goTypes = []interface{}{
	(Command)(0),            // 0: kar.rpc.Command
	(*HistogramBounds)(nil), // 1: kar.rpc.HistogramBounds
	(*TargetSpec)(nil),      // 2: kar.rpc.TargetSpec
	(*WorkerPoolConfig)(nil),// 3: kar.rpc.WorkerPoolConfig
	(*RegisterReq)(nil),     // 4: kar.rpc.RegisterReq
	(*RegisterResp)(nil),    // 5: kar.rpc.RegisterResp
	(*RateSubscribeReq)(nil),// 6: kar.rpc.RateSubscribeReq
	(*RateUpdate)(nil),      // 7: kar.rpc.RateUpdate
	(*StatsPush)(nil),       // 8: kar.rpc.StatsPush
	(*StatsAck)(nil),        // 9: kar.rpc.StatsAck
}

var _ = reflect.TypeOf

func init() {
	// Minimal init: register types so proto.Marshal/Unmarshal work via
	// the protoimpl path. Full file descriptor registration is skipped
	// because we don't have the raw descriptor bytes from protoc.
	// Regenerate with `make proto` when protoc is available.
}
