// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Hand-crafted: protoc not available on this system; see internal/rpc/proto/README.md
// source: kar.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const (
	KarMaster_Register_FullMethodName     = "/kar.rpc.KarMaster/Register"
	KarMaster_RateUpdates_FullMethodName  = "/kar.rpc.KarMaster/RateUpdates"
	KarMaster_Stats_FullMethodName        = "/kar.rpc.KarMaster/Stats"
)

// KarMasterClient is the client API for KarMaster service.
type KarMasterClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	RateUpdates(ctx context.Context, in *RateSubscribeReq, opts ...grpc.CallOption) (KarMaster_RateUpdatesClient, error)
	Stats(ctx context.Context, opts ...grpc.CallOption) (KarMaster_StatsClient, error)
}

type karMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewKarMasterClient(cc grpc.ClientConnInterface) KarMasterClient {
	return &karMasterClient{cc}
}

func (c *karMasterClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, KarMaster_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karMasterClient) RateUpdates(ctx context.Context, in *RateSubscribeReq, opts ...grpc.CallOption) (KarMaster_RateUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &KarMaster_ServiceDesc.Streams[0], KarMaster_RateUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &karMasterRateUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KarMaster_RateUpdatesClient interface {
	Recv() (*RateUpdate, error)
	grpc.ClientStream
}

type karMasterRateUpdatesClient struct {
	grpc.ClientStream
}

func (x *karMasterRateUpdatesClient) Recv() (*RateUpdate, error) {
	m := new(RateUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *karMasterClient) Stats(ctx context.Context, opts ...grpc.CallOption) (KarMaster_StatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &KarMaster_ServiceDesc.Streams[1], KarMaster_Stats_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	return &karMasterStatsClient{stream}, nil
}

type KarMaster_StatsClient interface {
	Send(*StatsPush) error
	CloseAndRecv() (*StatsAck, error)
	grpc.ClientStream
}

type karMasterStatsClient struct {
	grpc.ClientStream
}

func (x *karMasterStatsClient) Send(m *StatsPush) error {
	return x.ClientStream.SendMsg(m)
}

func (x *karMasterStatsClient) CloseAndRecv() (*StatsAck, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StatsAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KarMasterServer is the server API for KarMaster service.
type KarMasterServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	RateUpdates(*RateSubscribeReq, KarMaster_RateUpdatesServer) error
	Stats(KarMaster_StatsServer) error
	mustEmbedUnimplementedKarMasterServer()
}

// UnimplementedKarMasterServer must be embedded to have forward-compatible implementations.
type UnimplementedKarMasterServer struct{}

func (UnimplementedKarMasterServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedKarMasterServer) RateUpdates(*RateSubscribeReq, KarMaster_RateUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method RateUpdates not implemented")
}
func (UnimplementedKarMasterServer) Stats(KarMaster_StatsServer) error {
	return status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedKarMasterServer) mustEmbedUnimplementedKarMasterServer() {}

// UnsafeKarMasterServer may be embedded to opt out of forward compatibility.
type UnsafeKarMasterServer interface {
	mustEmbedUnimplementedKarMasterServer()
}

type KarMaster_RateUpdatesServer interface {
	Send(*RateUpdate) error
	grpc.ServerStream
}

type karMasterRateUpdatesServer struct {
	grpc.ServerStream
}

func (x *karMasterRateUpdatesServer) Send(m *RateUpdate) error {
	return x.ServerStream.SendMsg(m)
}

type KarMaster_StatsServer interface {
	SendAndClose(*StatsAck) error
	Recv() (*StatsPush, error)
	grpc.ServerStream
}

type karMasterStatsServer struct {
	grpc.ServerStream
}

func (x *karMasterStatsServer) SendAndClose(m *StatsAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *karMasterStatsServer) Recv() (*StatsPush, error) {
	m := new(StatsPush)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterKarMasterServer(s grpc.ServiceRegistrar, srv KarMasterServer) {
	s.RegisterService(&KarMaster_ServiceDesc, srv)
}

func _KarMaster_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KarMasterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KarMaster_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KarMasterServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KarMaster_RateUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RateSubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KarMasterServer).RateUpdates(m, &karMasterRateUpdatesServer{stream})
}

func _KarMaster_Stats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KarMasterServer).Stats(&karMasterStatsServer{stream})
}

// KarMaster_ServiceDesc is the grpc.ServiceDesc for KarMaster service.
var KarMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kar.rpc.KarMaster",
	HandlerType: (*KarMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _KarMaster_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RateUpdates",
			Handler:       _KarMaster_RateUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stats",
			Handler:       _KarMaster_Stats_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "kar.proto",
}
